services:
    mb_dashboard.project_repository:
        class:    "Doctrine\\ORM\\EntityRepository"
        factory:  [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:
            - "MB\\DashboardBundle\\Entity\\Project"

    mb_dashboard.project_manager:
        class: "MB\\DashboardBundle\\Manager\\ProjectManager"
        arguments: ["@doctrine.orm.entity_manager", "@mb_dashboard.project_repository", "@mb_dashboard.connectors"]


    mb_dashboard.connectors:
        class: "MB\\DashboardBundle\\Service\\ServiceConnector"
        arguments: ["%mb_dashboard%"]
