<?php

namespace MB\DashboardBundle\Repository;

/**
 * SourceGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
